# Generated by Django 4.2.1 on 2023-08-10 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vantablack', '0010_commentviews_share_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentviews',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vantablack.postviews'),
        ),
        migrations.AlterField(
            model_name='commentviews',
            name='share_post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vantablack.share_post'),
        ),
        migrations.CreateModel(
            name='save_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_save', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vantablack.postviews')),
                ('user_save', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
